<?php

use App\Distrito;
use Illuminate\Database\Seeder;

class DistritosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Distrito::create(['id' => 1, 'name' => 'Carmen', 'zona_id' => '10101', 'canton_id' => 1]);
        Distrito::create(['id' => 2, 'name' => 'Merced', 'zona_id' => '10102', 'canton_id' => 1]);
        Distrito::create(['id' => 3, 'name' => 'Hospital', 'zona_id' => '10103', 'canton_id' => 1]);
        Distrito::create(['id' => 4, 'name' => 'Catedral', 'zona_id' => '10104', 'canton_id' => 1]);
        Distrito::create(['id' => 5, 'name' => 'Zapote', 'zona_id' => '10105', 'canton_id' => 1]);
        Distrito::create(['id' => 6, 'name' => 'San Francisco de Dos Ríos', 'zona_id' => '10106', 'canton_id' => 1]);
        Distrito::create(['id' => 7, 'name' => 'Uruca', 'zona_id' => '10107', 'canton_id' => 1]);
        Distrito::create(['id' => 8, 'name' => 'Mata Redonda', 'zona_id' => '10108', 'canton_id' => 1]);
        Distrito::create(['id' => 9, 'name' => 'Pavas', 'zona_id' => '10109', 'canton_id' => 1]);
        Distrito::create(['id' => 10, 'name' => 'Hatillo', 'zona_id' => '10110', 'canton_id' => 1]);
        Distrito::create(['id' => 11, 'name' => 'San Sebastían', 'zona_id' => '10111', 'canton_id' => 1]);
        Distrito::create(['id' => 12, 'name' => 'Escazú', 'zona_id' => '10201', 'canton_id' => 2]);
        Distrito::create(['id' => 13, 'name' => 'San Antonio', 'zona_id' => '10202', 'canton_id' => 2]);
        Distrito::create(['id' => 14, 'name' => 'San Rafael', 'zona_id' => '10203', 'canton_id' => 2]);
        Distrito::create(['id' => 15, 'name' => 'Desamparados', 'zona_id' => '10301', 'canton_id' => 3]);
        Distrito::create(['id' => 16, 'name' => 'San Miguel', 'zona_id' => '10302', 'canton_id' => 3]);
        Distrito::create(['id' => 17, 'name' => 'San Juan de Dios', 'zona_id' => '10303', 'canton_id' => 3]);
        Distrito::create(['id' => 18, 'name' => 'San Rafael Arriba', 'zona_id' => '10304', 'canton_id' => 3]);
        Distrito::create(['id' => 19, 'name' => 'San Antonio', 'zona_id' => '10305', 'canton_id' => 3]);
        Distrito::create(['id' => 20, 'name' => 'Frailes', 'zona_id' => '10306', 'canton_id' => 3]);
        Distrito::create(['id' => 21, 'name' => 'Patarrá', 'zona_id' => '10307', 'canton_id' => 3]);
        Distrito::create(['id' => 22, 'name' => 'San Cristobal', 'zona_id' => '10308', 'canton_id' => 3]);
        Distrito::create(['id' => 23, 'name' => 'Rosario', 'zona_id' => '10309', 'canton_id' => 3]);
        Distrito::create(['id' => 24, 'name' => 'Damas', 'zona_id' => '10310', 'canton_id' => 3]);
        Distrito::create(['id' => 25, 'name' => 'San Rafael Abajo', 'zona_id' => '10311', 'canton_id' => 3]);
        Distrito::create(['id' => 26, 'name' => 'Gravilias', 'zona_id' => '10312', 'canton_id' => 3]);
        Distrito::create(['id' => 27, 'name' => 'Los Guido', 'zona_id' => '10313', 'canton_id' => 3]);
        Distrito::create(['id' => 28, 'name' => 'Santiago', 'zona_id' => '10401', 'canton_id' => 4]);
        Distrito::create(['id' => 29, 'name' => 'Mercedes Sur', 'zona_id' => '10402', 'canton_id' => 4]);
        Distrito::create(['id' => 30, 'name' => 'Barbacoas', 'zona_id' => '10403', 'canton_id' => 4]);
        Distrito::create(['id' => 31, 'name' => 'Grifo Alto', 'zona_id' => '10404', 'canton_id' => 4]);
        Distrito::create(['id' => 32, 'name' => 'San Rafael', 'zona_id' => '10405', 'canton_id' => 4]);
        Distrito::create(['id' => 33, 'name' => 'Candelarita', 'zona_id' => '10406', 'canton_id' => 4]);
        Distrito::create(['id' => 34, 'name' => 'Desamparaditos', 'zona_id' => '10407', 'canton_id' => 4]);
        Distrito::create(['id' => 35, 'name' => 'San Antonio', 'zona_id' => '10408', 'canton_id' => 4]);
        Distrito::create(['id' => 36, 'name' => 'Chires', 'zona_id' => '10409', 'canton_id' => 4]);
        Distrito::create(['id' => 37, 'name' => 'San Marcos', 'zona_id' => '10501', 'canton_id' => 5]);
        Distrito::create(['id' => 38, 'name' => 'San Lorenzo', 'zona_id' => '10502', 'canton_id' => 5]);
        Distrito::create(['id' => 39, 'name' => 'San Carlos', 'zona_id' => '10503', 'canton_id' => 5]);
        Distrito::create(['id' => 40, 'name' => 'Aserrí', 'zona_id' => '10601', 'canton_id' => 6]);
        Distrito::create(['id' => 41, 'name' => 'Tarbaca', 'zona_id' => '10602', 'canton_id' => 6]);
        Distrito::create(['id' => 42, 'name' => 'Vuelta de Jorco', 'zona_id' => '10603', 'canton_id' => 6]);
        Distrito::create(['id' => 43, 'name' => 'San Gabriel', 'zona_id' => '10604', 'canton_id' => 6]);
        Distrito::create(['id' => 44, 'name' => 'Legua', 'zona_id' => '10605', 'canton_id' => 6]);
        Distrito::create(['id' => 45, 'name' => 'Monterrey', 'zona_id' => '10606', 'canton_id' => 6]);
        Distrito::create(['id' => 46, 'name' => 'Salitrillos', 'zona_id' => '10607', 'canton_id' => 6]);
        Distrito::create(['id' => 47, 'name' => 'Colón', 'zona_id' => '10701', 'canton_id' => 7]);
        Distrito::create(['id' => 48, 'name' => 'Guayabo', 'zona_id' => '10702', 'canton_id' => 7]);
        Distrito::create(['id' => 49, 'name' => 'Tabarcia', 'zona_id' => '10703', 'canton_id' => 7]);
        Distrito::create(['id' => 50, 'name' => 'Piedras Negras', 'zona_id' => '10704', 'canton_id' => 7]);
        Distrito::create(['id' => 51, 'name' => 'Picagres', 'zona_id' => '10705', 'canton_id' => 7]);
        Distrito::create(['id' => 52, 'name' => 'Jaris', 'zona_id' => '10706', 'canton_id' => 7]);
        Distrito::create(['id' => 53, 'name' => 'Quitirrisí', 'zona_id' => '10707', 'canton_id' => 7]);
        Distrito::create(['id' => 54, 'name' => 'Guadalupe', 'zona_id' => '10801', 'canton_id' => 8]);
        Distrito::create(['id' => 55, 'name' => 'San Francisco', 'zona_id' => '10802', 'canton_id' => 8]);
        Distrito::create(['id' => 56, 'name' => 'Calle Blancos', 'zona_id' => '10803', 'canton_id' => 8]);
        Distrito::create(['id' => 57, 'name' => 'Mata de Plátano', 'zona_id' => '10804', 'canton_id' => 8]);
        Distrito::create(['id' => 58, 'name' => 'Ipís', 'zona_id' => '10805', 'canton_id' => 8]);
        Distrito::create(['id' => 59, 'name' => 'Rancho Redondo', 'zona_id' => '10806', 'canton_id' => 8]);
        Distrito::create(['id' => 60, 'name' => 'Purral', 'zona_id' => '10807', 'canton_id' => 8]);
        Distrito::create(['id' => 61, 'name' => 'Santa Ana', 'zona_id' => '10901', 'canton_id' => 9]);
        Distrito::create(['id' => 62, 'name' => 'Salitral', 'zona_id' => '10902', 'canton_id' => 9]);
        Distrito::create(['id' => 63, 'name' => 'Pozos', 'zona_id' => '10903', 'canton_id' => 9]);
        Distrito::create(['id' => 64, 'name' => 'Uruca', 'zona_id' => '10904', 'canton_id' => 9]);
        Distrito::create(['id' => 65, 'name' => 'Piedades', 'zona_id' => '10905', 'canton_id' => 9]);
        Distrito::create(['id' => 66, 'name' => 'Brasil', 'zona_id' => '10906', 'canton_id' => 9]);
        Distrito::create(['id' => 67, 'name' => 'Alajuelita', 'zona_id' => '11001', 'canton_id' => 10]);
        Distrito::create(['id' => 68, 'name' => 'San Josecito', 'zona_id' => '11002', 'canton_id' => 10]);
        Distrito::create(['id' => 69, 'name' => 'San Antonio', 'zona_id' => '11003', 'canton_id' => 10]);
        Distrito::create(['id' => 70, 'name' => 'Concepción', 'zona_id' => '11004', 'canton_id' => 10]);
        Distrito::create(['id' => 71, 'name' => 'San Felipe', 'zona_id' => '11005', 'canton_id' => 10]);
        Distrito::create(['id' => 72, 'name' => 'San Isidro', 'zona_id' => '11101', 'canton_id' => 11]);
        Distrito::create(['id' => 73, 'name' => 'San Rafael', 'zona_id' => '11102', 'canton_id' => 11]);
        Distrito::create(['id' => 74, 'name' => 'Dulce Nombre de Jesús', 'zona_id' => '11103', 'canton_id' => 11]);
        Distrito::create(['id' => 75, 'name' => 'Patalillo', 'zona_id' => '11104', 'canton_id' => 11]);
        Distrito::create(['id' => 76, 'name' => 'Cascajal', 'zona_id' => '11105', 'canton_id' => 11]);
        Distrito::create(['id' => 77, 'name' => 'San Ignacio', 'zona_id' => '11201', 'canton_id' => 12]);
        Distrito::create(['id' => 78, 'name' => 'Guaitil', 'zona_id' => '11202', 'canton_id' => 12]);
        Distrito::create(['id' => 79, 'name' => 'Palmichal', 'zona_id' => '11203', 'canton_id' => 12]);
        Distrito::create(['id' => 80, 'name' => 'Cangrejal', 'zona_id' => '11204', 'canton_id' => 12]);
        Distrito::create(['id' => 81, 'name' => 'Sabanillas', 'zona_id' => '11205', 'canton_id' => 12]);
        Distrito::create(['id' => 82, 'name' => 'San Juan', 'zona_id' => '11301', 'canton_id' => 13]);
        Distrito::create(['id' => 83, 'name' => 'Cinco Esquinas', 'zona_id' => '11302', 'canton_id' => 13]);
        Distrito::create(['id' => 84, 'name' => 'Anselmo Llorente', 'zona_id' => '11303', 'canton_id' => 13]);
        Distrito::create(['id' => 85, 'name' => 'León XIII', 'zona_id' => '11304', 'canton_id' => 13]);
        Distrito::create(['id' => 86, 'name' => 'Colima', 'zona_id' => '11305', 'canton_id' => 13]);
        Distrito::create(['id' => 87, 'name' => 'San Vicente', 'zona_id' => '11401', 'canton_id' => 14]);
        Distrito::create(['id' => 88, 'name' => 'San Jerónimo', 'zona_id' => '11402', 'canton_id' => 14]);
        Distrito::create(['id' => 89, 'name' => 'La Trinidad', 'zona_id' => '11403', 'canton_id' => 14]);
        Distrito::create(['id' => 90, 'name' => 'San Pedro', 'zona_id' => '11501', 'canton_id' => 15]);
        Distrito::create(['id' => 91, 'name' => 'Sabanilla', 'zona_id' => '11502', 'canton_id' => 15]);
        Distrito::create(['id' => 92, 'name' => 'Mercedes', 'zona_id' => '11503', 'canton_id' => 15]);
        Distrito::create(['id' => 93, 'name' => 'San Rafael', 'zona_id' => '11504', 'canton_id' => 15]);
        Distrito::create(['id' => 94, 'name' => 'San Pablo', 'zona_id' => '11601', 'canton_id' => 16]);
        Distrito::create(['id' => 95, 'name' => 'San Pedro', 'zona_id' => '11602', 'canton_id' => 16]);
        Distrito::create(['id' => 96, 'name' => 'San Juan de Mata', 'zona_id' => '11603', 'canton_id' => 16]);
        Distrito::create(['id' => 97, 'name' => 'San Luis', 'zona_id' => '11604', 'canton_id' => 16]);
        Distrito::create(['id' => 98, 'name' => 'Carara', 'zona_id' => '11605', 'canton_id' => 16]);
        Distrito::create(['id' => 99, 'name' => 'Santa María', 'zona_id' => '11701', 'canton_id' => 17]);
        Distrito::create(['id' => 100, 'name' => 'Jardín', 'zona_id' => '11702', 'canton_id' => 17]);
        Distrito::create(['id' => 101, 'name' => 'Copey', 'zona_id' => '11703', 'canton_id' => 17]);
        Distrito::create(['id' => 102, 'name' => 'Curridabat', 'zona_id' => '11801', 'canton_id' => 18]);
        Distrito::create(['id' => 103, 'name' => 'Granadilla', 'zona_id' => '11802', 'canton_id' => 18]);
        Distrito::create(['id' => 104, 'name' => 'Sánchez', 'zona_id' => '11803', 'canton_id' => 18]);
        Distrito::create(['id' => 105, 'name' => 'Tirrases', 'zona_id' => '11804', 'canton_id' => 18]);
        Distrito::create(['id' => 106, 'name' => 'San Isidro de El General', 'zona_id' => '11901', 'canton_id' => 19]);
        Distrito::create(['id' => 107, 'name' => 'El General', 'zona_id' => '11902', 'canton_id' => 19]);
        Distrito::create(['id' => 108, 'name' => 'Daniel Flores', 'zona_id' => '11903', 'canton_id' => 19]);
        Distrito::create(['id' => 109, 'name' => 'Rivas', 'zona_id' => '11904', 'canton_id' => 19]);
        Distrito::create(['id' => 110, 'name' => 'San Pedro', 'zona_id' => '11905', 'canton_id' => 19]);
        Distrito::create(['id' => 111, 'name' => 'Platanares', 'zona_id' => '11906', 'canton_id' => 19]);
        Distrito::create(['id' => 112, 'name' => 'Pejibaye', 'zona_id' => '11907', 'canton_id' => 19]);
        Distrito::create(['id' => 113, 'name' => 'Cajón', 'zona_id' => '11908', 'canton_id' => 19]);
        Distrito::create(['id' => 114, 'name' => 'Barú', 'zona_id' => '11909', 'canton_id' => 19]);
        Distrito::create(['id' => 115, 'name' => 'Río Nuevo', 'zona_id' => '11910', 'canton_id' => 19]);
        Distrito::create(['id' => 116, 'name' => 'Páramo', 'zona_id' => '11911', 'canton_id' => 19]);
        Distrito::create(['id' => 117, 'name' => 'La Amistad', 'zona_id' => '11912', 'canton_id' => 19]);
        Distrito::create(['id' => 118, 'name' => 'San Pablo', 'zona_id' => '12001', 'canton_id' => 20]);
        Distrito::create(['id' => 119, 'name' => 'San Andrés', 'zona_id' => '12002', 'canton_id' => 20]);
        Distrito::create(['id' => 120, 'name' => 'Llano Bonito', 'zona_id' => '12003', 'canton_id' => 20]);
        Distrito::create(['id' => 121, 'name' => 'San Isidro', 'zona_id' => '12004', 'canton_id' => 20]);
        Distrito::create(['id' => 122, 'name' => 'Santa Cruz', 'zona_id' => '12005', 'canton_id' => 20]);
        Distrito::create(['id' => 123, 'name' => 'San Antonio', 'zona_id' => '12006', 'canton_id' => 20]);
        Distrito::create(['id' => 124, 'name' => 'Alajuela', 'zona_id' => '20101', 'canton_id' => 21]);
        Distrito::create(['id' => 125, 'name' => 'San José', 'zona_id' => '20102', 'canton_id' => 21]);
        Distrito::create(['id' => 126, 'name' => 'Carrizal', 'zona_id' => '20103', 'canton_id' => 21]);
        Distrito::create(['id' => 127, 'name' => 'San Antonio', 'zona_id' => '20104', 'canton_id' => 21]);
        Distrito::create(['id' => 128, 'name' => 'Guácima', 'zona_id' => '20105', 'canton_id' => 21]);
        Distrito::create(['id' => 129, 'name' => 'San Isidro', 'zona_id' => '20106', 'canton_id' => 21]);
        Distrito::create(['id' => 130, 'name' => 'Sabanilla', 'zona_id' => '20107', 'canton_id' => 21]);
        Distrito::create(['id' => 131, 'name' => 'San Rafael', 'zona_id' => '20108', 'canton_id' => 21]);
        Distrito::create(['id' => 132, 'name' => 'Río Segundo', 'zona_id' => '20109', 'canton_id' => 21]);
        Distrito::create(['id' => 133, 'name' => 'Desamparados', 'zona_id' => '20110', 'canton_id' => 21]);
        Distrito::create(['id' => 134, 'name' => 'Turrúcares', 'zona_id' => '20111', 'canton_id' => 21]);
        Distrito::create(['id' => 135, 'name' => 'Tambor', 'zona_id' => '20112', 'canton_id' => 21]);
        Distrito::create(['id' => 136, 'name' => 'Garita', 'zona_id' => '20113', 'canton_id' => 21]);
        Distrito::create(['id' => 137, 'name' => 'Sarapiquí', 'zona_id' => '20114', 'canton_id' => 21]);
        Distrito::create(['id' => 138, 'name' => 'San Ramón', 'zona_id' => '20201', 'canton_id' => 22]);
        Distrito::create(['id' => 139, 'name' => 'Santiago', 'zona_id' => '20202', 'canton_id' => 22]);
        Distrito::create(['id' => 140, 'name' => 'San Juan', 'zona_id' => '20203', 'canton_id' => 22]);
        Distrito::create(['id' => 141, 'name' => 'Piedades Norte', 'zona_id' => '20204', 'canton_id' => 22]);
        Distrito::create(['id' => 142, 'name' => 'Piedades Sur', 'zona_id' => '20205', 'canton_id' => 22]);
        Distrito::create(['id' => 143, 'name' => 'San Rafael', 'zona_id' => '20206', 'canton_id' => 22]);
        Distrito::create(['id' => 144, 'name' => 'San Isidro', 'zona_id' => '20207', 'canton_id' => 22]);
        Distrito::create(['id' => 145, 'name' => 'Ángeles', 'zona_id' => '20208', 'canton_id' => 22]);
        Distrito::create(['id' => 146, 'name' => 'Alfaro', 'zona_id' => '20209', 'canton_id' => 22]);
        Distrito::create(['id' => 147, 'name' => 'Volio', 'zona_id' => '20210', 'canton_id' => 22]);
        Distrito::create(['id' => 148, 'name' => 'Concepción', 'zona_id' => '20211', 'canton_id' => 22]);
        Distrito::create(['id' => 149, 'name' => 'Zapotal', 'zona_id' => '20212', 'canton_id' => 22]);
        Distrito::create(['id' => 150, 'name' => 'Peñas Blancas', 'zona_id' => '20213', 'canton_id' => 22]);
        Distrito::create(['id' => 151, 'name' => 'San Lorenzo', 'zona_id' => '20214', 'canton_id' => 22]);
        Distrito::create(['id' => 152, 'name' => 'Grecia', 'zona_id' => '20301', 'canton_id' => 23]);
        Distrito::create(['id' => 153, 'name' => 'San Isidro', 'zona_id' => '20302', 'canton_id' => 23]);
        Distrito::create(['id' => 154, 'name' => 'San José', 'zona_id' => '20303', 'canton_id' => 23]);
        Distrito::create(['id' => 155, 'name' => 'San Roque', 'zona_id' => '20304', 'canton_id' => 23]);
        Distrito::create(['id' => 156, 'name' => 'Tacares', 'zona_id' => '20305', 'canton_id' => 23]);
        Distrito::create(['id' => 157, 'name' => 'Puente de Piedra', 'zona_id' => '20307', 'canton_id' => 23]);
        Distrito::create(['id' => 158, 'name' => 'Bolívar', 'zona_id' => '20308', 'canton_id' => 23]);
        Distrito::create(['id' => 159, 'name' => 'San Mateo', 'zona_id' => '20401', 'canton_id' => 24]);
        Distrito::create(['id' => 160, 'name' => 'Desmonte', 'zona_id' => '20402', 'canton_id' => 24]);
        Distrito::create(['id' => 161, 'name' => 'Jesús María', 'zona_id' => '20403', 'canton_id' => 24]);
        Distrito::create(['id' => 162, 'name' => 'Labrador', 'zona_id' => '20404', 'canton_id' => 24]);
        Distrito::create(['id' => 163, 'name' => 'Atenas', 'zona_id' => '20501', 'canton_id' => 25]);
        Distrito::create(['id' => 164, 'name' => 'Jesús', 'zona_id' => '20502', 'canton_id' => 25]);
        Distrito::create(['id' => 165, 'name' => 'Mercedes', 'zona_id' => '20503', 'canton_id' => 25]);
        Distrito::create(['id' => 166, 'name' => 'San Isidro', 'zona_id' => '20504', 'canton_id' => 25]);
        Distrito::create(['id' => 167, 'name' => 'Concepción', 'zona_id' => '20505', 'canton_id' => 25]);
        Distrito::create(['id' => 168, 'name' => 'San José', 'zona_id' => '20506', 'canton_id' => 25]);
        Distrito::create(['id' => 169, 'name' => 'Santa Eulalia', 'zona_id' => '20507', 'canton_id' => 25]);
        Distrito::create(['id' => 170, 'name' => 'Escobal', 'zona_id' => '20508', 'canton_id' => 25]);
        Distrito::create(['id' => 171, 'name' => 'Naranjo', 'zona_id' => '20601', 'canton_id' => 26]);
        Distrito::create(['id' => 172, 'name' => 'San Miguel', 'zona_id' => '20602', 'canton_id' => 26]);
        Distrito::create(['id' => 173, 'name' => 'San José', 'zona_id' => '20603', 'canton_id' => 26]);
        Distrito::create(['id' => 174, 'name' => 'Cirrí Sur', 'zona_id' => '20604', 'canton_id' => 26]);
        Distrito::create(['id' => 175, 'name' => 'San Jerónimo', 'zona_id' => '20605', 'canton_id' => 26]);
        Distrito::create(['id' => 176, 'name' => 'San Juan', 'zona_id' => '20606', 'canton_id' => 26]);
        Distrito::create(['id' => 177, 'name' => 'El Rosario', 'zona_id' => '20607', 'canton_id' => 26]);
        Distrito::create(['id' => 178, 'name' => 'Palmitos', 'zona_id' => '20608', 'canton_id' => 26]);
        Distrito::create(['id' => 179, 'name' => 'Palmares', 'zona_id' => '20701', 'canton_id' => 27]);
        Distrito::create(['id' => 180, 'name' => 'Zaragoza', 'zona_id' => '20702', 'canton_id' => 27]);
        Distrito::create(['id' => 181, 'name' => 'Buenos Aires', 'zona_id' => '20703', 'canton_id' => 27]);
        Distrito::create(['id' => 182, 'name' => 'Santiago', 'zona_id' => '20704', 'canton_id' => 27]);
        Distrito::create(['id' => 183, 'name' => 'Candelaria', 'zona_id' => '20705', 'canton_id' => 27]);
        Distrito::create(['id' => 184, 'name' => 'Esquipulas', 'zona_id' => '20706', 'canton_id' => 27]);
        Distrito::create(['id' => 185, 'name' => 'La Granja', 'zona_id' => '20707', 'canton_id' => 27]);
        Distrito::create(['id' => 186, 'name' => 'San Pedro', 'zona_id' => '20801', 'canton_id' => 28]);
        Distrito::create(['id' => 187, 'name' => 'San Juan', 'zona_id' => '20802', 'canton_id' => 28]);
        Distrito::create(['id' => 188, 'name' => 'San Rafael', 'zona_id' => '20803', 'canton_id' => 28]);
        Distrito::create(['id' => 189, 'name' => 'Carrillos', 'zona_id' => '20804', 'canton_id' => 28]);
        Distrito::create(['id' => 190, 'name' => 'Sabana Redonda', 'zona_id' => '20805', 'canton_id' => 28]);
        Distrito::create(['id' => 191, 'name' => 'Orotina', 'zona_id' => '20901', 'canton_id' => 29]);
        Distrito::create(['id' => 192, 'name' => 'El Mastate', 'zona_id' => '20902', 'canton_id' => 29]);
        Distrito::create(['id' => 193, 'name' => 'Hacienda Vieja', 'zona_id' => '20903', 'canton_id' => 29]);
        Distrito::create(['id' => 194, 'name' => 'Coyolar', 'zona_id' => '20904', 'canton_id' => 29]);
        Distrito::create(['id' => 195, 'name' => 'La Ceiba', 'zona_id' => '20905', 'canton_id' => 29]);
        Distrito::create(['id' => 196, 'name' => 'Quesada', 'zona_id' => '21001', 'canton_id' => 30]);
        Distrito::create(['id' => 197, 'name' => 'Florencia', 'zona_id' => '21002', 'canton_id' => 30]);
        Distrito::create(['id' => 198, 'name' => 'Buenavista', 'zona_id' => '21003', 'canton_id' => 30]);
        Distrito::create(['id' => 199, 'name' => 'Aguas Zarcas', 'zona_id' => '21004', 'canton_id' => 30]);
        Distrito::create(['id' => 200, 'name' => 'Venecia', 'zona_id' => '21005', 'canton_id' => 30]);
        Distrito::create(['id' => 201, 'name' => 'Pital', 'zona_id' => '21006', 'canton_id' => 30]);
        Distrito::create(['id' => 202, 'name' => 'La Fortuna', 'zona_id' => '21007', 'canton_id' => 30]);
        Distrito::create(['id' => 203, 'name' => 'La Tigra', 'zona_id' => '21008', 'canton_id' => 30]);
        Distrito::create(['id' => 204, 'name' => 'La Palmera', 'zona_id' => '21009', 'canton_id' => 30]);
        Distrito::create(['id' => 205, 'name' => 'Venado', 'zona_id' => '21010', 'canton_id' => 30]);
        Distrito::create(['id' => 206, 'name' => 'Cutris', 'zona_id' => '21011', 'canton_id' => 30]);
        Distrito::create(['id' => 207, 'name' => 'Monterrey', 'zona_id' => '21012', 'canton_id' => 30]);
        Distrito::create(['id' => 208, 'name' => 'Pocosol', 'zona_id' => '21013', 'canton_id' => 30]);
        Distrito::create(['id' => 209, 'name' => 'Zarcero', 'zona_id' => '21101', 'canton_id' => 31]);
        Distrito::create(['id' => 210, 'name' => 'Laguna', 'zona_id' => '21102', 'canton_id' => 31]);
        Distrito::create(['id' => 211, 'name' => 'Tapesco', 'zona_id' => '21103', 'canton_id' => 31]);
        Distrito::create(['id' => 212, 'name' => 'Guadalupe', 'zona_id' => '21104', 'canton_id' => 31]);
        Distrito::create(['id' => 213, 'name' => 'Palmira', 'zona_id' => '21105', 'canton_id' => 31]);
        Distrito::create(['id' => 214, 'name' => 'Zapote', 'zona_id' => '21106', 'canton_id' => 31]);
        Distrito::create(['id' => 215, 'name' => 'Brisas', 'zona_id' => '21107', 'canton_id' => 31]);
        Distrito::create(['id' => 216, 'name' => 'Sarchí Norte', 'zona_id' => '21201', 'canton_id' => 32]);
        Distrito::create(['id' => 217, 'name' => 'Sarchí Sur', 'zona_id' => '21202', 'canton_id' => 32]);
        Distrito::create(['id' => 218, 'name' => 'Toro Amarillo', 'zona_id' => '21203', 'canton_id' => 32]);
        Distrito::create(['id' => 219, 'name' => 'San Pedro', 'zona_id' => '21204', 'canton_id' => 32]);
        Distrito::create(['id' => 220, 'name' => 'Rodríguez', 'zona_id' => '21205', 'canton_id' => 32]);
        Distrito::create(['id' => 221, 'name' => 'Upala', 'zona_id' => '21301', 'canton_id' => 33]);
        Distrito::create(['id' => 222, 'name' => 'Aguas Claras', 'zona_id' => '21302', 'canton_id' => 33]);
        Distrito::create(['id' => 223, 'name' => 'San José o Pizote', 'zona_id' => '21303', 'canton_id' => 33]);
        Distrito::create(['id' => 224, 'name' => 'Bijagua', 'zona_id' => '21304', 'canton_id' => 33]);
        Distrito::create(['id' => 225, 'name' => 'Delicias', 'zona_id' => '21305', 'canton_id' => 33]);
        Distrito::create(['id' => 226, 'name' => 'Dos Ríos', 'zona_id' => '21306', 'canton_id' => 33]);
        Distrito::create(['id' => 227, 'name' => 'Yolillal', 'zona_id' => '21307', 'canton_id' => 33]);
        Distrito::create(['id' => 228, 'name' => 'Canalete', 'zona_id' => '21308', 'canton_id' => 33]);
        Distrito::create(['id' => 229, 'name' => 'Los Chiles', 'zona_id' => '21401', 'canton_id' => 34]);
        Distrito::create(['id' => 230, 'name' => 'Caño Negro', 'zona_id' => '21402', 'canton_id' => 34]);
        Distrito::create(['id' => 231, 'name' => 'El Amparo', 'zona_id' => '21403', 'canton_id' => 34]);
        Distrito::create(['id' => 232, 'name' => 'San Jorge', 'zona_id' => '21404', 'canton_id' => 34]);
        Distrito::create(['id' => 233, 'name' => 'San Rafael', 'zona_id' => '21501', 'canton_id' => 35]);
        Distrito::create(['id' => 234, 'name' => 'Buenavista', 'zona_id' => '21502', 'canton_id' => 35]);
        Distrito::create(['id' => 235, 'name' => 'Cote', 'zona_id' => '21503', 'canton_id' => 35]);
        Distrito::create(['id' => 236, 'name' => 'Katira', 'zona_id' => '21504', 'canton_id' => 35]);
        Distrito::create(['id' => 237, 'name' => 'Río Cuarto', 'zona_id' => '21601', 'canton_id' => 36]);
        Distrito::create(['id' => 238, 'name' => 'Santa Rita', 'zona_id' => '21602', 'canton_id' => 36]);
        Distrito::create(['id' => 239, 'name' => 'Santa Isabel', 'zona_id' => '21603', 'canton_id' => 36]);
        Distrito::create(['id' => 240, 'name' => 'Oriental', 'zona_id' => '30101', 'canton_id' => 37]);
        Distrito::create(['id' => 241, 'name' => 'Occidental', 'zona_id' => '30102', 'canton_id' => 37]);
        Distrito::create(['id' => 242, 'name' => 'Carmen', 'zona_id' => '30103', 'canton_id' => 37]);
        Distrito::create(['id' => 243, 'name' => 'San Nicolás', 'zona_id' => '30104', 'canton_id' => 37]);
        Distrito::create(['id' => 244, 'name' => 'Aguacaliente o San Francisco', 'zona_id' => '30105', 'canton_id' => 37]);
        Distrito::create(['id' => 245, 'name' => 'Guadalupe o Arenilla', 'zona_id' => '30106', 'canton_id' => 37]);
        Distrito::create(['id' => 246, 'name' => 'Corralillo', 'zona_id' => '30107', 'canton_id' => 37]);
        Distrito::create(['id' => 247, 'name' => 'Tierra Blanca', 'zona_id' => '30108', 'canton_id' => 37]);
        Distrito::create(['id' => 248, 'name' => 'Dulce Nombre', 'zona_id' => '30109', 'canton_id' => 37]);
        Distrito::create(['id' => 249, 'name' => 'Llano Grande', 'zona_id' => '30110', 'canton_id' => 37]);
        Distrito::create(['id' => 250, 'name' => 'Quebradilla', 'zona_id' => '30111', 'canton_id' => 37]);
        Distrito::create(['id' => 251, 'name' => 'Paraíso', 'zona_id' => '30201', 'canton_id' => 38]);
        Distrito::create(['id' => 252, 'name' => 'Santiago', 'zona_id' => '30202', 'canton_id' => 38]);
        Distrito::create(['id' => 253, 'name' => 'Orosi', 'zona_id' => '30203', 'canton_id' => 38]);
        Distrito::create(['id' => 254, 'name' => 'Cachí', 'zona_id' => '30204', 'canton_id' => 38]);
        Distrito::create(['id' => 255, 'name' => 'Llanos de Santa Lucía', 'zona_id' => '30205', 'canton_id' => 38]);
        Distrito::create(['id' => 256, 'name' => 'Tres Ríos', 'zona_id' => '30301', 'canton_id' => 39]);
        Distrito::create(['id' => 257, 'name' => 'San Diego', 'zona_id' => '30302', 'canton_id' => 39]);
        Distrito::create(['id' => 258, 'name' => 'San Juan', 'zona_id' => '30303', 'canton_id' => 39]);
        Distrito::create(['id' => 259, 'name' => 'San Rafael', 'zona_id' => '30304', 'canton_id' => 39]);
        Distrito::create(['id' => 260, 'name' => 'Concepción', 'zona_id' => '30305', 'canton_id' => 39]);
        Distrito::create(['id' => 261, 'name' => 'Dulce Nombre', 'zona_id' => '30306', 'canton_id' => 39]);
        Distrito::create(['id' => 262, 'name' => 'San Ramón', 'zona_id' => '30307', 'canton_id' => 39]);
        Distrito::create(['id' => 263, 'name' => 'Río Azul', 'zona_id' => '30308', 'canton_id' => 39]);
        Distrito::create(['id' => 264, 'name' => 'Juan Viñas', 'zona_id' => '30401', 'canton_id' => 40]);
        Distrito::create(['id' => 265, 'name' => 'Tucurrique', 'zona_id' => '30402', 'canton_id' => 40]);
        Distrito::create(['id' => 266, 'name' => 'Pejibaye', 'zona_id' => '30403', 'canton_id' => 40]);
        Distrito::create(['id' => 267, 'name' => 'Turrialba', 'zona_id' => '30501', 'canton_id' => 41]);
        Distrito::create(['id' => 268, 'name' => 'La Suiza', 'zona_id' => '30502', 'canton_id' => 41]);
        Distrito::create(['id' => 269, 'name' => 'Peralta', 'zona_id' => '30503', 'canton_id' => 41]);
        Distrito::create(['id' => 270, 'name' => 'Santa Cruz', 'zona_id' => '30504', 'canton_id' => 41]);
        Distrito::create(['id' => 271, 'name' => 'Santa Teresita', 'zona_id' => '30505', 'canton_id' => 41]);
        Distrito::create(['id' => 272, 'name' => 'Pavones', 'zona_id' => '30506', 'canton_id' => 41]);
        Distrito::create(['id' => 273, 'name' => 'Tuis', 'zona_id' => '30507', 'canton_id' => 41]);
        Distrito::create(['id' => 274, 'name' => 'Tayutic', 'zona_id' => '30508', 'canton_id' => 41]);
        Distrito::create(['id' => 275, 'name' => 'Santa Rosa', 'zona_id' => '30509', 'canton_id' => 41]);
        Distrito::create(['id' => 276, 'name' => 'Tres Equis', 'zona_id' => '30510', 'canton_id' => 41]);
        Distrito::create(['id' => 277, 'name' => 'La Isabel', 'zona_id' => '30511', 'canton_id' => 41]);
        Distrito::create(['id' => 278, 'name' => 'Chirripó', 'zona_id' => '30512', 'canton_id' => 41]);
        Distrito::create(['id' => 279, 'name' => 'Pacayas', 'zona_id' => '30601', 'canton_id' => 42]);
        Distrito::create(['id' => 280, 'name' => 'Cervantes', 'zona_id' => '30602', 'canton_id' => 42]);
        Distrito::create(['id' => 281, 'name' => 'Capellades', 'zona_id' => '30603', 'canton_id' => 42]);
        Distrito::create(['id' => 282, 'name' => 'San Rafael', 'zona_id' => '30701', 'canton_id' => 43]);
        Distrito::create(['id' => 283, 'name' => 'Cot', 'zona_id' => '30702', 'canton_id' => 43]);
        Distrito::create(['id' => 284, 'name' => 'Potrero Cerrado', 'zona_id' => '30703', 'canton_id' => 43]);
        Distrito::create(['id' => 285, 'name' => 'Cipreses', 'zona_id' => '30704', 'canton_id' => 43]);
        Distrito::create(['id' => 286, 'name' => 'Santa Rosa', 'zona_id' => '30705', 'canton_id' => 43]);
        Distrito::create(['id' => 287, 'name' => 'El Tejar', 'zona_id' => '30801', 'canton_id' => 44]);
        Distrito::create(['id' => 288, 'name' => 'San Isidro', 'zona_id' => '30802', 'canton_id' => 44]);
        Distrito::create(['id' => 289, 'name' => 'Tobosi', 'zona_id' => '30803', 'canton_id' => 44]);
        Distrito::create(['id' => 290, 'name' => 'Patio de Agua', 'zona_id' => '30804', 'canton_id' => 44]);
        Distrito::create(['id' => 291, 'name' => 'Heredia', 'zona_id' => '40101', 'canton_id' => 45]);
        Distrito::create(['id' => 292, 'name' => 'Mercedes', 'zona_id' => '40102', 'canton_id' => 45]);
        Distrito::create(['id' => 293, 'name' => 'San Francisco', 'zona_id' => '40103', 'canton_id' => 45]);
        Distrito::create(['id' => 294, 'name' => 'Ulloa', 'zona_id' => '40104', 'canton_id' => 45]);
        Distrito::create(['id' => 295, 'name' => 'Varablanca', 'zona_id' => '40105', 'canton_id' => 45]);
        Distrito::create(['id' => 296, 'name' => 'Barva', 'zona_id' => '40201', 'canton_id' => 46]);
        Distrito::create(['id' => 297, 'name' => 'San Pedro', 'zona_id' => '40202', 'canton_id' => 46]);
        Distrito::create(['id' => 298, 'name' => 'San Pablo', 'zona_id' => '40203', 'canton_id' => 46]);
        Distrito::create(['id' => 299, 'name' => 'San Roque', 'zona_id' => '40204', 'canton_id' => 46]);
        Distrito::create(['id' => 300, 'name' => 'Santa Lucía', 'zona_id' => '40205', 'canton_id' => 46]);
        Distrito::create(['id' => 301, 'name' => 'San José de la Montaña', 'zona_id' => '40206', 'canton_id' => 46]);
        Distrito::create(['id' => 302, 'name' => 'Santo Domingo', 'zona_id' => '40301', 'canton_id' => 47]);
        Distrito::create(['id' => 303, 'name' => 'San Vicente', 'zona_id' => '40302', 'canton_id' => 47]);
        Distrito::create(['id' => 304, 'name' => 'San Miguel', 'zona_id' => '40303', 'canton_id' => 47]);
        Distrito::create(['id' => 305, 'name' => 'Paracito', 'zona_id' => '40304', 'canton_id' => 47]);
        Distrito::create(['id' => 306, 'name' => 'Santo Tomás', 'zona_id' => '40305', 'canton_id' => 47]);
        Distrito::create(['id' => 307, 'name' => 'Santa Rosa', 'zona_id' => '40306', 'canton_id' => 47]);
        Distrito::create(['id' => 308, 'name' => 'Tures', 'zona_id' => '40307', 'canton_id' => 47]);
        Distrito::create(['id' => 309, 'name' => 'Pará', 'zona_id' => '40308', 'canton_id' => 47]);
        Distrito::create(['id' => 310, 'name' => 'Santa Bárbara', 'zona_id' => '40401', 'canton_id' => 48]);
        Distrito::create(['id' => 311, 'name' => 'San Pedro', 'zona_id' => '40402', 'canton_id' => 48]);
        Distrito::create(['id' => 312, 'name' => 'San Juan', 'zona_id' => '40403', 'canton_id' => 48]);
        Distrito::create(['id' => 313, 'name' => 'Jesús', 'zona_id' => '40404', 'canton_id' => 48]);
        Distrito::create(['id' => 314, 'name' => 'Santo Domingo', 'zona_id' => '40405', 'canton_id' => 48]);
        Distrito::create(['id' => 315, 'name' => 'Purabá', 'zona_id' => '40406', 'canton_id' => 48]);
        Distrito::create(['id' => 316, 'name' => 'San Rafael', 'zona_id' => '40501', 'canton_id' => 49]);
        Distrito::create(['id' => 317, 'name' => 'San Josecito', 'zona_id' => '40502', 'canton_id' => 49]);
        Distrito::create(['id' => 318, 'name' => 'Santiago', 'zona_id' => '40503', 'canton_id' => 49]);
        Distrito::create(['id' => 319, 'name' => 'Ángeles', 'zona_id' => '40504', 'canton_id' => 49]);
        Distrito::create(['id' => 320, 'name' => 'Concepción', 'zona_id' => '40505', 'canton_id' => 49]);
        Distrito::create(['id' => 321, 'name' => 'San Isidro', 'zona_id' => '40601', 'canton_id' => 50]);
        Distrito::create(['id' => 322, 'name' => 'San José', 'zona_id' => '40602', 'canton_id' => 50]);
        Distrito::create(['id' => 323, 'name' => 'Concepción', 'zona_id' => '40603', 'canton_id' => 50]);
        Distrito::create(['id' => 324, 'name' => 'San Francisco', 'zona_id' => '40604', 'canton_id' => 50]);
        Distrito::create(['id' => 325, 'name' => 'San Antonio', 'zona_id' => '40701', 'canton_id' => 51]);
        Distrito::create(['id' => 326, 'name' => 'La Ribera', 'zona_id' => '40702', 'canton_id' => 51]);
        Distrito::create(['id' => 327, 'name' => 'La Asunción', 'zona_id' => '40703', 'canton_id' => 51]);
        Distrito::create(['id' => 328, 'name' => 'San Joaquín', 'zona_id' => '40801', 'canton_id' => 52]);
        Distrito::create(['id' => 329, 'name' => 'Barrantes', 'zona_id' => '40802', 'canton_id' => 52]);
        Distrito::create(['id' => 330, 'name' => 'Llorente', 'zona_id' => '40803', 'canton_id' => 52]);
        Distrito::create(['id' => 331, 'name' => 'San Pablo', 'zona_id' => '40901', 'canton_id' => 53]);
        Distrito::create(['id' => 332, 'name' => 'Rincón de Sabanilla', 'zona_id' => '40902', 'canton_id' => 53]);
        Distrito::create(['id' => 333, 'name' => 'Puerto Viejo', 'zona_id' => '41001', 'canton_id' => 54]);
        Distrito::create(['id' => 334, 'name' => 'La Virgen', 'zona_id' => '41002', 'canton_id' => 54]);
        Distrito::create(['id' => 335, 'name' => 'Las Horquetas', 'zona_id' => '41003', 'canton_id' => 54]);
        Distrito::create(['id' => 336, 'name' => 'Llanuras del Gaspar', 'zona_id' => '41004', 'canton_id' => 54]);
        Distrito::create(['id' => 337, 'name' => 'Cureña', 'zona_id' => '41005', 'canton_id' => 54]);
        Distrito::create(['id' => 338, 'name' => 'Liberia', 'zona_id' => '50101', 'canton_id' => 55]);
        Distrito::create(['id' => 339, 'name' => 'Cañas Dulces', 'zona_id' => '50102', 'canton_id' => 55]);
        Distrito::create(['id' => 340, 'name' => 'Mayorga', 'zona_id' => '50103', 'canton_id' => 55]);
        Distrito::create(['id' => 341, 'name' => 'Nacascolo', 'zona_id' => '50104', 'canton_id' => 55]);
        Distrito::create(['id' => 342, 'name' => 'Curubandé', 'zona_id' => '50105', 'canton_id' => 55]);
        Distrito::create(['id' => 343, 'name' => 'Nicoya', 'zona_id' => '50201', 'canton_id' => 56]);
        Distrito::create(['id' => 344, 'name' => 'Mansión', 'zona_id' => '50202', 'canton_id' => 56]);
        Distrito::create(['id' => 345, 'name' => 'San Antonio', 'zona_id' => '50203', 'canton_id' => 56]);
        Distrito::create(['id' => 346, 'name' => 'Quebrada Honda', 'zona_id' => '50204', 'canton_id' => 56]);
        Distrito::create(['id' => 347, 'name' => 'Sámara', 'zona_id' => '50205', 'canton_id' => 56]);
        Distrito::create(['id' => 348, 'name' => 'Nosara', 'zona_id' => '50206', 'canton_id' => 56]);
        Distrito::create(['id' => 349, 'name' => 'Belén de Nosarita', 'zona_id' => '50207', 'canton_id' => 56]);
        Distrito::create(['id' => 350, 'name' => 'Santa Cruz', 'zona_id' => '50301', 'canton_id' => 57]);
        Distrito::create(['id' => 351, 'name' => 'Bolsón', 'zona_id' => '50302', 'canton_id' => 57]);
        Distrito::create(['id' => 352, 'name' => 'Veintisiete de Abril', 'zona_id' => '50303', 'canton_id' => 57]);
        Distrito::create(['id' => 353, 'name' => 'Tempate', 'zona_id' => '50304', 'canton_id' => 57]);
        Distrito::create(['id' => 354, 'name' => 'Cartagena', 'zona_id' => '50305', 'canton_id' => 57]);
        Distrito::create(['id' => 355, 'name' => 'Cuajiniquil', 'zona_id' => '50306', 'canton_id' => 57]);
        Distrito::create(['id' => 356, 'name' => 'Diriá', 'zona_id' => '50307', 'canton_id' => 57]);
        Distrito::create(['id' => 357, 'name' => 'Cabo Velas', 'zona_id' => '50308', 'canton_id' => 57]);
        Distrito::create(['id' => 358, 'name' => 'Tamarindo', 'zona_id' => '50309', 'canton_id' => 57]);
        Distrito::create(['id' => 359, 'name' => 'Bagaces', 'zona_id' => '50401', 'canton_id' => 58]);
        Distrito::create(['id' => 360, 'name' => 'La Fortuna', 'zona_id' => '50402', 'canton_id' => 58]);
        Distrito::create(['id' => 361, 'name' => 'Mogote', 'zona_id' => '50403', 'canton_id' => 58]);
        Distrito::create(['id' => 362, 'name' => 'Río Naranjo', 'zona_id' => '50404', 'canton_id' => 58]);
        Distrito::create(['id' => 363, 'name' => 'Filadelfia', 'zona_id' => '50501', 'canton_id' => 59]);
        Distrito::create(['id' => 364, 'name' => 'Palmira', 'zona_id' => '50502', 'canton_id' => 59]);
        Distrito::create(['id' => 365, 'name' => 'Sardinal', 'zona_id' => '50503', 'canton_id' => 59]);
        Distrito::create(['id' => 366, 'name' => 'Belén', 'zona_id' => '50504', 'canton_id' => 59]);
        Distrito::create(['id' => 367, 'name' => 'Cañas', 'zona_id' => '50601', 'canton_id' => 60]);
        Distrito::create(['id' => 368, 'name' => 'Palmira', 'zona_id' => '50602', 'canton_id' => 60]);
        Distrito::create(['id' => 369, 'name' => 'San Miguel', 'zona_id' => '50603', 'canton_id' => 60]);
        Distrito::create(['id' => 370, 'name' => 'Bebedero', 'zona_id' => '50604', 'canton_id' => 60]);
        Distrito::create(['id' => 371, 'name' => 'Porozal', 'zona_id' => '50605', 'canton_id' => 60]);
        Distrito::create(['id' => 372, 'name' => 'Las Juntas', 'zona_id' => '50701', 'canton_id' => 61]);
        Distrito::create(['id' => 373, 'name' => 'Sierra', 'zona_id' => '50702', 'canton_id' => 61]);
        Distrito::create(['id' => 374, 'name' => 'San Juan', 'zona_id' => '50703', 'canton_id' => 61]);
        Distrito::create(['id' => 375, 'name' => 'Colorado', 'zona_id' => '50704', 'canton_id' => 61]);
        Distrito::create(['id' => 376, 'name' => 'Tilarán', 'zona_id' => '50801', 'canton_id' => 62]);
        Distrito::create(['id' => 377, 'name' => 'Quebrada Grande', 'zona_id' => '50802', 'canton_id' => 62]);
        Distrito::create(['id' => 378, 'name' => 'Tronadora', 'zona_id' => '50803', 'canton_id' => 62]);
        Distrito::create(['id' => 379, 'name' => 'Santa Rosa', 'zona_id' => '50804', 'canton_id' => 62]);
        Distrito::create(['id' => 380, 'name' => 'Líbano', 'zona_id' => '50805', 'canton_id' => 62]);
        Distrito::create(['id' => 381, 'name' => 'Tierras Morenas', 'zona_id' => '50806', 'canton_id' => 62]);
        Distrito::create(['id' => 382, 'name' => 'Arenal', 'zona_id' => '50807', 'canton_id' => 62]);
        Distrito::create(['id' => 383, 'name' => 'Carmona', 'zona_id' => '50901', 'canton_id' => 63]);
        Distrito::create(['id' => 384, 'name' => 'Santa Rita', 'zona_id' => '50902', 'canton_id' => 63]);
        Distrito::create(['id' => 385, 'name' => 'Zapotal', 'zona_id' => '50903', 'canton_id' => 63]);
        Distrito::create(['id' => 386, 'name' => 'San Pablo', 'zona_id' => '50904', 'canton_id' => 63]);
        Distrito::create(['id' => 387, 'name' => 'Porvenir', 'zona_id' => '50905', 'canton_id' => 63]);
        Distrito::create(['id' => 388, 'name' => 'Bejuco', 'zona_id' => '50906', 'canton_id' => 63]);
        Distrito::create(['id' => 389, 'name' => 'La Cruz', 'zona_id' => '51001', 'canton_id' => 64]);
        Distrito::create(['id' => 390, 'name' => 'Santa Cecilia', 'zona_id' => '51002', 'canton_id' => 64]);
        Distrito::create(['id' => 391, 'name' => 'La Garita', 'zona_id' => '51003', 'canton_id' => 64]);
        Distrito::create(['id' => 392, 'name' => 'Santa Elena', 'zona_id' => '51004', 'canton_id' => 64]);
        Distrito::create(['id' => 393, 'name' => 'Hojancha', 'zona_id' => '51101', 'canton_id' => 65]);
        Distrito::create(['id' => 394, 'name' => 'Monte Romo', 'zona_id' => '51102', 'canton_id' => 65]);
        Distrito::create(['id' => 395, 'name' => 'Puerto Carrillo', 'zona_id' => '51103', 'canton_id' => 65]);
        Distrito::create(['id' => 396, 'name' => 'Huacas', 'zona_id' => '51104', 'canton_id' => 65]);
        Distrito::create(['id' => 397, 'name' => 'Matambú', 'zona_id' => '51105', 'canton_id' => 65]);
        Distrito::create(['id' => 398, 'name' => 'Puntarenas', 'zona_id' => '60101', 'canton_id' => 66]);
        Distrito::create(['id' => 399, 'name' => 'Pitahaya', 'zona_id' => '60102', 'canton_id' => 66]);
        Distrito::create(['id' => 400, 'name' => 'Chomes', 'zona_id' => '60103', 'canton_id' => 66]);
        Distrito::create(['id' => 401, 'name' => 'Lepanto', 'zona_id' => '60104', 'canton_id' => 66]);
        Distrito::create(['id' => 402, 'name' => 'Paquera', 'zona_id' => '60105', 'canton_id' => 66]);
        Distrito::create(['id' => 403, 'name' => 'Manzanillo', 'zona_id' => '60106', 'canton_id' => 66]);
        Distrito::create(['id' => 404, 'name' => 'Guacimal', 'zona_id' => '60107', 'canton_id' => 66]);
        Distrito::create(['id' => 405, 'name' => 'Barranca', 'zona_id' => '60108', 'canton_id' => 66]);
        Distrito::create(['id' => 406, 'name' => 'Monte Verde', 'zona_id' => '60109', 'canton_id' => 66]);
        Distrito::create(['id' => 407, 'name' => 'Isla del Coco', 'zona_id' => '60110', 'canton_id' => 66]);
        Distrito::create(['id' => 408, 'name' => 'Cóbano', 'zona_id' => '60111', 'canton_id' => 66]);
        Distrito::create(['id' => 409, 'name' => 'Chacarita', 'zona_id' => '60112', 'canton_id' => 66]);
        Distrito::create(['id' => 410, 'name' => 'Chira', 'zona_id' => '60113', 'canton_id' => 66]);
        Distrito::create(['id' => 411, 'name' => 'Acapulco', 'zona_id' => '60114', 'canton_id' => 66]);
        Distrito::create(['id' => 412, 'name' => 'El Roble', 'zona_id' => '60115', 'canton_id' => 66]);
        Distrito::create(['id' => 413, 'name' => 'Arancibia', 'zona_id' => '60116', 'canton_id' => 66]);
        Distrito::create(['id' => 414, 'name' => 'Espíritu Santo', 'zona_id' => '60201', 'canton_id' => 67]);
        Distrito::create(['id' => 415, 'name' => 'San Juan Grande', 'zona_id' => '60202', 'canton_id' => 67]);
        Distrito::create(['id' => 416, 'name' => 'Macacona', 'zona_id' => '60203', 'canton_id' => 67]);
        Distrito::create(['id' => 417, 'name' => 'San Rafael', 'zona_id' => '60204', 'canton_id' => 67]);
        Distrito::create(['id' => 418, 'name' => 'San Jerónimo', 'zona_id' => '60205', 'canton_id' => 67]);
        Distrito::create(['id' => 419, 'name' => 'Caldera', 'zona_id' => '60206', 'canton_id' => 67]);
        Distrito::create(['id' => 420, 'name' => 'Buenos Aires', 'zona_id' => '60301', 'canton_id' => 68]);
        Distrito::create(['id' => 421, 'name' => 'Volcán', 'zona_id' => '60302', 'canton_id' => 68]);
        Distrito::create(['id' => 422, 'name' => 'Potrero Grande', 'zona_id' => '60303', 'canton_id' => 68]);
        Distrito::create(['id' => 423, 'name' => 'Boruca', 'zona_id' => '60304', 'canton_id' => 68]);
        Distrito::create(['id' => 424, 'name' => 'Pilas', 'zona_id' => '60305', 'canton_id' => 68]);
        Distrito::create(['id' => 425, 'name' => 'Colinas', 'zona_id' => '60306', 'canton_id' => 68]);
        Distrito::create(['id' => 426, 'name' => 'Chánguena', 'zona_id' => '60307', 'canton_id' => 68]);
        Distrito::create(['id' => 427, 'name' => 'Biolley', 'zona_id' => '60308', 'canton_id' => 68]);
        Distrito::create(['id' => 428, 'name' => 'Brunka', 'zona_id' => '60309', 'canton_id' => 68]);
        Distrito::create(['id' => 429, 'name' => 'Miramar', 'zona_id' => '60401', 'canton_id' => 69]);
        Distrito::create(['id' => 430, 'name' => 'La Unión', 'zona_id' => '60402', 'canton_id' => 69]);
        Distrito::create(['id' => 431, 'name' => 'San Isidro', 'zona_id' => '60403', 'canton_id' => 69]);
        Distrito::create(['id' => 432, 'name' => 'Puerto Cortés', 'zona_id' => '60501', 'canton_id' => 70]);
        Distrito::create(['id' => 433, 'name' => 'Palmar', 'zona_id' => '60502', 'canton_id' => 70]);
        Distrito::create(['id' => 434, 'name' => 'Sierpe', 'zona_id' => '60503', 'canton_id' => 70]);
        Distrito::create(['id' => 435, 'name' => 'Bahía Ballena', 'zona_id' => '60504', 'canton_id' => 70]);
        Distrito::create(['id' => 436, 'name' => 'Piedras Blancas', 'zona_id' => '60505', 'canton_id' => 70]);
        Distrito::create(['id' => 437, 'name' => 'Bahía Drake', 'zona_id' => '60506', 'canton_id' => 70]);
        Distrito::create(['id' => 438, 'name' => 'Quepos', 'zona_id' => '60601', 'canton_id' => 71]);
        Distrito::create(['id' => 439, 'name' => 'Savegre', 'zona_id' => '60602', 'canton_id' => 71]);
        Distrito::create(['id' => 440, 'name' => 'Naranjito', 'zona_id' => '60603', 'canton_id' => 71]);
        Distrito::create(['id' => 441, 'name' => 'Golfito', 'zona_id' => '60701', 'canton_id' => 72]);
        Distrito::create(['id' => 442, 'name' => 'Puerto Jiménez', 'zona_id' => '60702', 'canton_id' => 72]);
        Distrito::create(['id' => 443, 'name' => 'Guaycará', 'zona_id' => '60703', 'canton_id' => 72]);
        Distrito::create(['id' => 444, 'name' => 'Pavón', 'zona_id' => '60704', 'canton_id' => 72]);
        Distrito::create(['id' => 445, 'name' => 'San Vito', 'zona_id' => '60801', 'canton_id' => 73]);
        Distrito::create(['id' => 446, 'name' => 'Sabalito', 'zona_id' => '60802', 'canton_id' => 73]);
        Distrito::create(['id' => 447, 'name' => 'Agua Buena', 'zona_id' => '60803', 'canton_id' => 73]);
        Distrito::create(['id' => 448, 'name' => 'Limoncito', 'zona_id' => '60804', 'canton_id' => 73]);
        Distrito::create(['id' => 449, 'name' => 'Pittier', 'zona_id' => '60805', 'canton_id' => 73]);
        Distrito::create(['id' => 450, 'name' => 'Gutiérrez Braun', 'zona_id' => '60806', 'canton_id' => 73]);
        Distrito::create(['id' => 451, 'name' => 'Parrita', 'zona_id' => '60901', 'canton_id' => 74]);
        Distrito::create(['id' => 452, 'name' => 'Corredor', 'zona_id' => '61001', 'canton_id' => 75]);
        Distrito::create(['id' => 453, 'name' => 'La Cuesta', 'zona_id' => '61002', 'canton_id' => 75]);
        Distrito::create(['id' => 454, 'name' => 'Canoas', 'zona_id' => '61003', 'canton_id' => 75]);
        Distrito::create(['id' => 455, 'name' => 'Laurel', 'zona_id' => '61004', 'canton_id' => 75]);
        Distrito::create(['id' => 456, 'name' => 'Jacó', 'zona_id' => '61101', 'canton_id' => 76]);
        Distrito::create(['id' => 457, 'name' => 'Tárcoles', 'zona_id' => '61102', 'canton_id' => 76]);
        Distrito::create(['id' => 458, 'name' => 'Limón', 'zona_id' => '70101', 'canton_id' => 77]);
        Distrito::create(['id' => 459, 'name' => 'Valle La Estrella', 'zona_id' => '70102', 'canton_id' => 77]);
        Distrito::create(['id' => 460, 'name' => 'Río Blanco', 'zona_id' => '70103', 'canton_id' => 77]);
        Distrito::create(['id' => 461, 'name' => 'Matama', 'zona_id' => '70104', 'canton_id' => 77]);
        Distrito::create(['id' => 462, 'name' => 'Guápiles', 'zona_id' => '70201', 'canton_id' => 78]);
        Distrito::create(['id' => 463, 'name' => 'Jiménez', 'zona_id' => '70202', 'canton_id' => 78]);
        Distrito::create(['id' => 464, 'name' => 'Rita', 'zona_id' => '70203', 'canton_id' => 78]);
        Distrito::create(['id' => 465, 'name' => 'Roxana', 'zona_id' => '70204', 'canton_id' => 78]);
        Distrito::create(['id' => 466, 'name' => 'Cariari', 'zona_id' => '70205', 'canton_id' => 78]);
        Distrito::create(['id' => 467, 'name' => 'Colorado', 'zona_id' => '70206', 'canton_id' => 78]);
        Distrito::create(['id' => 468, 'name' => 'La Colonia', 'zona_id' => '70207', 'canton_id' => 78]);
        Distrito::create(['id' => 469, 'name' => 'Siquirres', 'zona_id' => '70301', 'canton_id' => 79]);
        Distrito::create(['id' => 470, 'name' => 'Pacuarito', 'zona_id' => '70302', 'canton_id' => 79]);
        Distrito::create(['id' => 471, 'name' => 'Florida', 'zona_id' => '70303', 'canton_id' => 79]);
        Distrito::create(['id' => 472, 'name' => 'Germania', 'zona_id' => '70304', 'canton_id' => 79]);
        Distrito::create(['id' => 473, 'name' => 'El Cairo', 'zona_id' => '70305', 'canton_id' => 79]);
        Distrito::create(['id' => 474, 'name' => 'Alegría', 'zona_id' => '70306', 'canton_id' => 79]);
        Distrito::create(['id' => 475, 'name' => 'Reventazón', 'zona_id' => '70307', 'canton_id' => 79]);
        Distrito::create(['id' => 476, 'name' => 'Bratsi', 'zona_id' => '70401', 'canton_id' => 80]);
        Distrito::create(['id' => 477, 'name' => 'Sixaola', 'zona_id' => '70402', 'canton_id' => 80]);
        Distrito::create(['id' => 478, 'name' => 'Cahuita', 'zona_id' => '70403', 'canton_id' => 80]);
        Distrito::create(['id' => 479, 'name' => 'Telire', 'zona_id' => '70404', 'canton_id' => 80]);
        Distrito::create(['id' => 480, 'name' => 'Matina', 'zona_id' => '70501', 'canton_id' => 81]);
        Distrito::create(['id' => 481, 'name' => 'Batán', 'zona_id' => '70502', 'canton_id' => 81]);
        Distrito::create(['id' => 482, 'name' => 'Carrandi', 'zona_id' => '70503', 'canton_id' => 81]);
        Distrito::create(['id' => 483, 'name' => 'Guácimo', 'zona_id' => '70601', 'canton_id' => 82]);
        Distrito::create(['id' => 484, 'name' => 'Mercedes', 'zona_id' => '70602', 'canton_id' => 82]);
        Distrito::create(['id' => 485, 'name' => 'Pocora', 'zona_id' => '70603', 'canton_id' => 82]);
        Distrito::create(['id' => 486, 'name' => 'Río Jiménez', 'zona_id' => '70604', 'canton_id' => 82]);
        Distrito::create(['id' => 487, 'name' => 'Duacarí', 'zona_id' => '70605', 'canton_id' => 82]);
    }
}
